language: php

matrix:
  include:
    - dist: precise
      sudo: false
    - dist: precise
      sudo: required
    - dist: trusty
      sudo: false
    - dist: trusty
      sudo: required
      
install: true
script:
  - npm --version
